apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-ui
  name: udagram-ui
  namespace: default
  selfLink: /api/v1/namespaces/default/services/udagram-ui
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: udagram-ui
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
